### ISSUE TITLE
URL/ Serveradresse der Original Gigaset Klicktel-Suche?

### ISSUE THREAD

**Issue by LeeBinder** [stelas/Anrufersuche#1]
Hallo Steffen. Vielen Dank erstmal für deine Version von Rolands Script!

Ich habe deine email-Adresse nicht gefunden, daher als Issue.

Ich bräuchte für mein Gigaset DL500A eine wichtige Info:
Was war (ist) die URL/ Serveradresse, die von der Firmware der Gigaset Basisstationen aus bei der ursprünglichen Klicktel-Suche gesendet wird? Also in der Form von:

Bsp.: https://klicktel.de/onlinetelefonbuch.php

oder ähnlich. Diese bräuchte ich.

Weißt du die, oder hast du in deinem DSL-Modem oder Router einen Netmonitor laufen und kannst kurz nochmal in deinem Gigaset auf klicktel zurückstellen, eine Dummy-Suche starten und in deinem Netmonitor schauen, welche URL versucht wird, aufzulösen?

Würde mir seehr weiterhelfen da das DL500A ja leider KEINE Hinzufügen-Funktion Einstellungen für einen zusätzlichen Provider hat .. :(

Danke und Grüße vom Bodensee,
Lee

**Comment by stelas** [comment]
Hi Lee,

Gigaset hat den Telefonbuchanbieter klickTel in Firmware 42.247 entfernt.
Die Rückwärtssuche wurde über [openapi.klicktel.de](http://openapi.klicktel.de) angeboten.

Viel Erfolg
Steffen

**Comment by LeeBinder** [comment]
Danke Steffen für deine sofortige Rückmeldung. Die DL500A ist noch mit der vorherigen 41.xyz FW bestückt, für die Siemens schon seit einiger Zeit keine Aktualisierungen mehr gemacht hat, daher existiert darin der KT Eintrag noch.

Als nächstes muss ich schauen, wie ich in meiner 7312 Fritzbox einen redirect openapi.klicktel.de --> meine.domain/oertliche.php oder auch wenn erforderlich --> openapi.meine.domain hinbekomme

Mit Freetz? Oder OpenWRT? Falls du damit auch Erfahrung hast.

**Comment by stelas** [comment]
Im Prinzip DNS auf deinen Webserver umbiegen und mittels Access-Log den Skriptaufruf entsprechend nachbauen. Würde dazu einen Raspi nehmen und diesen in der Fritzbox als DNS-Server eintragen...

**Comment by LeeBinder** [comment]
Einen Rasperry Pi, echt jetzt? Du meinst darauf einen kleinen (Linux/ Apache) Webserver + das php Script, und dann den Pi ins LAN einbinden? Hmm das klingt für mich erstmal ziemlich exotisch - in die Richtung hätte ich nie gedacht.

Ich habe seit ein paar Stunden schon ein Freetz Base-Image auf meiner 7312 laufen. Mit dem package PrivProxy + transparent proxy + noch ggfs. noch einem weiteren Modul, die i.d. nächsten Tagen dazukommen sollen, sollen komplette URL redirects funktionieren.

Die Commnity-Dokumentationen darüber sind nicht optimal, und grad muss ich sowieso noch auf das fertige Freetz-Image f.d. 7312 warten. Ich halt dich auf dem Laufenden, wie sich dieses Projekt entfaltet :) Auf jeden Fall schonmal danke für deine kreativen Tips 👍

**Comment by LeeBinder** [comment]
Bislang noch kein Durchbrauch:
https://www.digital-eliteboard.com/threads/url-umleiten-url-redirect-mit-freetz-bitte-um-anleitung.476370/#post-3607483

**Comment by LeeBinder** [comment]
@stelas Schau mal, ggfs. via EEPROM Phonebook Provider?

![Screenshot_2019-06-17 Configuration DL500A](https://user-images.githubusercontent.com/39203497/59571972-1dc80a80-90aa-11e9-868e-1d2b3a42e321.png)

via http://ip-adresse/settings_services_online_directory.html

Hast du eine Idee wie man das für oertliche.php konfiguriert? Bislang habe ich keinen Erfolg.

(mein posting: https://www.ip-phone-forum.de/threads/pers%C3%B6nliches-online-telefonbuch-via-xml.190928/#post-2331345)

**Comment by stelas** [comment]
Versuch mal als Service-URL 'http://...' und den Haken bei 'Nickname for...' rauszunehmen. Auf meiner Anlage sieht diese versteckte Konfigurationsseite anders aus:
![gigaset](https://user-images.githubusercontent.com/15674535/59622494-fc126600-9131-11e9-8262-7cbeb19a5be5.jpg)

**Comment by LeeBinder** [comment]
ja prima dankeschön. Ich bin grad auf Achse und kann mich in ein paar Tagen wieder melden.

**Comment by LeeBinder** [comment]
Bin wieder zurück. Erstmal sehr gute Nachricht - **50% Erfolg**: kurz bevor ich losfuhr kam noch ein Anruf v. einer Firma, die NICHT in meinem lokalen fonbuch gespeichert war, und der Name wurde dennoch korrekt angezeigt (so wie in dasoertliche.de). Wenn ich aber nach einem Namen + Ort via Gigaset/ Netztelefonbuch suche, läuft sich die Suche tot.

[EDIT]: Ja, habe als Service-URL [http://...](http://...) und den Haken bei 'Nickname for...' rausgenommen.

Jetzt muss ich wohl für mein DL500A das Script so umschreiben, dass die XML-Antwort das richtige Format hat.

Mein Beitrag ist [hier](https://www.ip-phone-forum.de/threads/url-umleiten-url-redirect-mit-freetz-bitte-um-anleitung.303567/page-2#post-2331705), falls du irgend einen Idee hast 🥇

**Comment by LeeBinder** [comment]
http**s**://../oertliche.php geht wohl generell nicht, da die Gigasets http erwarten. Wenn du Lust hast könntest du bei Gelegenheit testweise http://tuja.yoga/stelas/oertliche.php eintragen und versuchen.

Geht bei dir denn generell auch das Netz-Telefonbuch über Tasteneingabe, oder NUR die Namensanzeige auf dem Gigaset, wenn du von jemandem angerufen wirst der seine Nummer öffentlich hat?

Übrigens:

> Die Rückwärtssuche wurde über [openapi.klicktel.de](http://openapi.klicktel.de) angeboten.

von https://www.ip-phone-forum.de/threads/ldap-verzeichnisdienst.148079/post-943067:

> Für das Klickte Telefonbuch wird `http://api.klicktel.de/gigasetpb/1.0/search.php` aufgerufen 

 via Log auf meiner Fritzbox ist das auch so. Aber sollte das mit der EEPROM Seite komplett funktionieren, muss der Aufruf sowieso nicht nachgebastelt werden.
